### ISSUE TITLE
No XDebug 8.0 & 8.1

### ISSUE THREAD

**Issue by ddv88** [llaumgui/docker-images-php-fpm#11]
```
PHP Version 8.0.21
Configure Command	'./configure' '--build=x86_64-linux-musl' 
'--with-config-file-path=/usr/local/etc/php' 
'--with-config-file-scan-dir=/usr/local/etc/php/conf.d' 
'--enable-option-checking=fatal' 
'--with-mhash' 
'--with-pic' 
'--enable-ftp' 
'--enable-mbstring'
 '--enable-mysqlnd' 
'--with-password-argon2' 
'--with-sodium=shared'
 '--with-pdo-sqlite=/usr' 
'--with-sqlite3=/usr'
 '--with-curl' 
'--with-iconv=/usr'
 '--with-openssl' 
'--with-readline'
 '--with-zlib' 
'--disable-phpdbg'
 '--with-pear'
 '--disable-cgi'
 '--enable-fpm'
 '--with-fpm-user=www-data'
 '--with-fpm-group=www-data' 
'build_alias=x86_64-linux-musl'

Debug Build	no
```

`FROM llaumgui/php:8.0`

```
build:
      context: ./docker/build/
      dockerfile: phpfpm
      args:
        DOCKER_PHP_ENABLE_XDEBUG: 'on'
```

`'--disable-phpdbg'` ? Why?
